### ISSUE TITLE
adapter spec is broken

### ISSUE THREAD

**Issue by douglasrodrigo** [mkristian/dm-hibernate-adapter#16]
Gist with log execution
https://gist.github.com/1252425

**Comment by pietia** [comment]
maybe we should try turn off logger in specs?

**Comment by douglasrodrigo** [comment]
Pietia, I think that the problem is on specs environment, if you try to do something with eventlog will work normally.

**Comment by pietia** [comment]
@douglasrodrigo pull latest changes, i have turned off @mkristian 's hack . Specs looks much better right now

**Comment by douglasrodrigo** [comment]
Much better now :)
[INFO] 64 examples, 3 failures

I'll look to solve remained failures.
Thanks dude.

**Comment by pietia** [comment]
can you try to build gem (mvn install) and copy over gem (by hand) to
demo/ and try to run it? It looks like something is wrong with
creating objects (read, update works).

**Comment by douglasrodrigo** [comment]
same problem here

[INFO] NativeException (org.hibernate.MappingException: Unknown entity: org.jruby.RubyObject):
[INFO]   app/controllers/users_controller.rb:46:in `create'
[INFO]   app/controllers/users_controller.rb:45:in`create'

**Comment by pietia** [comment]
can you revert my last commit (apply Kristian's hack) and try again?
It didn't helped me

**Comment by douglasrodrigo** [comment]
I've removed your last commit and also didn't work :(
Same problem:

[INFO] NativeException (org.hibernate.MappingException: Unknown entity: org.jruby.RubyObject):
[INFO]   app/controllers/users_controller.rb:46:in `create'
[INFO]   app/controllers/users_controller.rb:45:in`create'

**Comment by pietia** [comment]
Great! :)

**Comment by pietia** [comment]
Closing, looks fine now.

**Comment by mkristian** [comment]
after pull I still get failures ? do I do something wrong ?

TOTAL: 61 passing; 3 failing; 0 pending

**Comment by pietia** [comment]
that's "fine" state :) Previously all were red

**Comment by pietia** [comment]
Missing parts are associations and it's a topic of other ticket, i think

**Comment by mkristian** [comment]
:-) OK
